insert into MOCK_DATA (title, description, author) values ('The Legend of Awesomest Maximus', 'Body dysmorphic disorder', 'Rachael Cowperthwaite');
insert into MOCK_DATA (title, description, author) values ('Livid (Livide)', 'Other specified joint disorders, unspecified hand', 'Thedric Alton');
insert into MOCK_DATA (title, description, author) values ('Committed', 'Passenger in three-wheeled motor vehicle injured in noncollision transport accident in traffic accident, sequela', 'Corliss Brimelow');
insert into MOCK_DATA (title, description, author) values ('American History X', 'Traumatic rupture of right radiocarpal ligament', 'Clem MacCheyne');
insert into MOCK_DATA (title, description, author) values ('Ten Little Indians', 'Exposure to other specified factors, initial encounter', 'Osmund Rouse');
insert into MOCK_DATA (title, description, author) values ('Waterland', 'Displaced spiral fracture of shaft of ulna, right arm, subsequent encounter for closed fracture with routine healing', 'Emmye Showler');
insert into MOCK_DATA (title, description, author) values ('Fire on the Mountain', 'Other fracture of upper end of left tibia, subsequent encounter for closed fracture with routine healing', 'Lefty Barnham');
insert into MOCK_DATA (title, description, author) values ('Dawn of the Planet of the Apes', 'Adverse effect of other psychotropic drugs, initial encounter', 'Clevey Jeff');
insert into MOCK_DATA (title, description, author) values ('Model Shop', 'Perforation due to foreign body accidentally left in body following injection or immunization', 'Boony Lamberti');
insert into MOCK_DATA (title, description, author) values ('Dancing at Lughnasa', 'Other fracture of unspecified talus, initial encounter for closed fracture', 'Reube Matthius');
insert into MOCK_DATA (title, description, author) values ('Fools Rush In', 'Polyhydramnios, third trimester, not applicable or unspecified', 'Shayla Dunstall');
insert into MOCK_DATA (title, description, author) values ('20,000 Leagues Under the Sea', 'Strain of muscle, fascia and tendon of the posterior muscle group at thigh level, right thigh, sequela', 'Dacey Brands');
insert into MOCK_DATA (title, description, author) values ('Butley', 'Juvenile rheumatoid arthritis with systemic onset, unspecified ankle and foot', 'Tania McElmurray');
insert into MOCK_DATA (title, description, author) values ('Wondrous Oblivion', 'Paralytic lagophthalmos right eye, unspecified eyelid', 'Haskell Pinel');
insert into MOCK_DATA (title, description, author) values ('Bride Came C.O.D., The', 'Postprocedural heart failure following other surgery', 'Demetri Sambath');
insert into MOCK_DATA (title, description, author) values ('9', 'Hematoma of pinna, right ear', 'Evelyn McCarl');
insert into MOCK_DATA (title, description, author) values ('Walk Hard: The Dewey Cox Story', 'Poisoning by, adverse effect of and underdosing of tricyclic and tetracyclic antidepressants', 'Persis Leist');
insert into MOCK_DATA (title, description, author) values ('Let''s Scare Jessica to Death', 'Unspecified foreign body in trachea causing asphyxiation, subsequent encounter', 'Maximilian Byrcher');
insert into MOCK_DATA (title, description, author) values ('Easy Wheels', 'Other hair color and hair shaft abnormalities', 'Bren Casol');
insert into MOCK_DATA (title, description, author) values ('Johnny English', 'Other snow-ski accident, sequela', 'Maribel Pechell');
insert into MOCK_DATA (title, description, author) values ('Rebecca of Sunnybrook Farm', 'Puncture wound without foreign body of left forearm, sequela', 'Gabie Celes');
insert into MOCK_DATA (title, description, author) values ('Used Cars', 'Laceration with foreign body of unspecified external genital organs, female, sequela', 'Weidar Amerighi');
insert into MOCK_DATA (title, description, author) values ('King Kong', 'Abrasion of abdomen, lower back, pelvis and external genitals', 'Norris Burbudge');
insert into MOCK_DATA (title, description, author) values ('Name for Evil, A', 'Rheumatic aortic valve diseases', 'Harriott Blazhevich');
insert into MOCK_DATA (title, description, author) values ('Rollover', 'Cafeteria of hospital as the place of occurrence of the external cause', 'Rustie Dumphy');
insert into MOCK_DATA (title, description, author) values ('Father of Invention', 'Infection due to gastric band procedure', 'Kimmie Grenshiels');
insert into MOCK_DATA (title, description, author) values ('That''s Life!', 'Nondisplaced trimalleolar fracture of unspecified lower leg, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing', 'Ellie Gillooly');
insert into MOCK_DATA (title, description, author) values ('Lured', 'Retrolental fibroplasia, right eye', 'Howie Pilley');
insert into MOCK_DATA (title, description, author) values ('Elena Undone', 'Insect bite (nonvenomous), right great toe, sequela', 'Joya Lewsley');
insert into MOCK_DATA (title, description, author) values ('Schizopolis', 'Ophthalmic devices associated with adverse incidents', 'Zorine Liebmann');
insert into MOCK_DATA (title, description, author) values ('Death Race 2000', 'Cellulitis and acute lymphangitis', 'Mel Ludwell');
insert into MOCK_DATA (title, description, author) values ('Bakhita', 'Displacement of indwelling urethral catheter, subsequent encounter', 'Rollo Smith');
insert into MOCK_DATA (title, description, author) values ('Johnson Family Vacation', 'Fall from, out of or through bridge, initial encounter', 'Jason Ledward');
insert into MOCK_DATA (title, description, author) values ('Princess Raccoon (Operetta tanuki goten)', 'Poisoning by other agents primarily affecting the cardiovascular system, accidental (unintentional)', 'Nanny Bunkle');
insert into MOCK_DATA (title, description, author) values ('Perfect Human, The (Perfekte Menneske, Det)', 'War operations involving explosion of torpedo, military personnel, subsequent encounter', 'Edwin Britnell');
insert into MOCK_DATA (title, description, author) values ('Oh, God! Book II', 'Transient synovitis, unspecified ankle and foot', 'Chrystal Menure');
insert into MOCK_DATA (title, description, author) values ('Tokyo-Ga', 'Other disorders of lacrimal gland', 'Urbain Buard');
insert into MOCK_DATA (title, description, author) values ('Rhythm of a Crime (Ritam zlocina)', 'Toxic effect of petroleum products, intentional self-harm, sequela', 'Gregor Birds');
insert into MOCK_DATA (title, description, author) values ('Monte Carlo', 'Mine or pit as the place of occurrence of the external cause', 'Eadith Gatch');
insert into MOCK_DATA (title, description, author) values ('Powaqqatsi', 'Adhesions due to foreign body accidentally left in body following unspecified procedure, subsequent encounter', 'Ulrika Obeney');
insert into MOCK_DATA (title, description, author) values ('Hijacking Catastrophe: 9/11, Fear & the Selling of American Empire', 'Burn of unspecified degree of left axilla, subsequent encounter', 'Yardley Bourgaize');
insert into MOCK_DATA (title, description, author) values ('Secretary', 'Displaced supracondylar fracture without intracondylar extension of lower end of right femur, sequela', 'Anastassia Havercroft');
insert into MOCK_DATA (title, description, author) values ('River, The', 'Unspecified fracture of fourth metacarpal bone, right hand, initial encounter for closed fracture', 'Annie Ritchman');
insert into MOCK_DATA (title, description, author) values ('4th Floor, The', 'Burn of first degree of left upper arm', 'Jules Obert');
insert into MOCK_DATA (title, description, author) values ('Oxygen', 'Contact with raccoon', 'Sibyl Halfpenny');
insert into MOCK_DATA (title, description, author) values ('Ill-Fated Love (Doomed Love) (Amor de Perdição)', 'Other disturbances of skin sensation', 'Reinwald McCheyne');
insert into MOCK_DATA (title, description, author) values ('What''s the Matter with Helen?', 'Displaced segmental fracture of shaft of unspecified femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion', 'Dottie Cosgriff');
insert into MOCK_DATA (title, description, author) values ('Greatest Show on Earth, The', 'Activity, roller coaster riding', 'Kettie Connachan');
insert into MOCK_DATA (title, description, author) values ('Dead Man Running', 'Nondisplaced spiral fracture of shaft of unspecified femur, subsequent encounter for open fracture type I or II with malunion', 'Emanuele Benediktovich');
insert into MOCK_DATA (title, description, author) values ('Cherry Orchard, The (Sakura no sono)', 'Mixed cellularity Hodgkin lymphoma, lymph nodes of multiple sites', 'Blanch Mollnar');
insert into MOCK_DATA (title, description, author) values ('Gay Deceivers, The', 'Congenital malformation of male genital organ, unspecified', 'Pietro Tonry');
insert into MOCK_DATA (title, description, author) values ('Unforgiven', 'Open bite of other specified part of neck, sequela', 'Dan McCrum');
insert into MOCK_DATA (title, description, author) values ('Amigo', 'Crushing injury of right little finger, initial encounter', 'Hyman Walsom');
insert into MOCK_DATA (title, description, author) values ('Fan, The', 'Diffuse large B-cell lymphoma, intrathoracic lymph nodes', 'Aymer Widdocks');
insert into MOCK_DATA (title, description, author) values ('Men, The', 'Sprain of other specified parts of left knee, subsequent encounter', 'Prentiss Hafner');
insert into MOCK_DATA (title, description, author) values ('Season for Miracles, A', 'Complications of other internal prosthetic devices, implants and grafts', 'Raimund Willgress');
insert into MOCK_DATA (title, description, author) values ('Killer Bean 2: The Party', 'Other subluxation of right shoulder joint, sequela', 'Darryl Mosco');
insert into MOCK_DATA (title, description, author) values ('Mosquito Coast, The', 'Malignant neoplasm of lower-outer quadrant of breast, female', 'Tallie Bussel');
insert into MOCK_DATA (title, description, author) values ('An American Tail: The Treasure of Manhattan Island', 'Central nervous system complications of anesthesia during the puerperium', 'Anny Geistmann');
insert into MOCK_DATA (title, description, author) values ('Weekend', 'Other specified injuries of vocal cord, sequela', 'Candice Lemmanbie');
insert into MOCK_DATA (title, description, author) values ('Good Job:  Stories of the FDNY, A', 'Abnormal electromyogram [EMG]', 'Deloria Shuxsmith');
insert into MOCK_DATA (title, description, author) values ('Chicken with Plums (Poulet aux prunes)', 'Laceration of muscle(s) and tendon(s) of the rotator cuff of left shoulder, initial encounter', 'Myrna Galloway');
insert into MOCK_DATA (title, description, author) values ('Visitors', 'Driver of heavy transport vehicle injured in collision with car, pick-up truck or van in nontraffic accident, subsequent encounter', 'Cathyleen Godden');
insert into MOCK_DATA (title, description, author) values ('Bird', 'Stress fracture, unspecified tibia and fibula, sequela', 'Susannah Loveridge');
insert into MOCK_DATA (title, description, author) values ('Wayne''s World', 'Female pseudohermaphroditism, not elsewhere classified', 'Cristi Idenden');
insert into MOCK_DATA (title, description, author) values ('Man of No Importance, A', 'Explosion of mine placed during war operations but exploding after cessation of hostilities', 'Dyanne Currum');
insert into MOCK_DATA (title, description, author) values ('Under the Domim Tree (Etz Hadomim Tafus)', 'Nondisplaced fracture of acromial process, right shoulder, initial encounter for open fracture', 'Adrea Gynni');
insert into MOCK_DATA (title, description, author) values ('The Well', 'Abrasion of left ear, initial encounter', 'Kasey Gaiford');
insert into MOCK_DATA (title, description, author) values ('Family Guy Presents: It''s a Trap', 'Other superficial bite of left lesser toe(s), sequela', 'Alvin McInnery');
insert into MOCK_DATA (title, description, author) values ('Nanook of the North', 'Unspecified injury of dorsal artery of unspecified foot, initial encounter', 'Laney Hamstead');
insert into MOCK_DATA (title, description, author) values ('Havre, Le', 'Retinopathy of prematurity, unspecified, bilateral', 'Bernardina Rand');
insert into MOCK_DATA (title, description, author) values ('Woman on Top', 'ABO incompatibility with hemolytic transfusion reaction, unspecified', 'Guy Husthwaite');
insert into MOCK_DATA (title, description, author) values ('Rose, The', 'Poisoning by other opioids, intentional self-harm', 'Aurore Wilprecht');
insert into MOCK_DATA (title, description, author) values ('Cat o'' Nine Tails, The (Gatto a nove code, Il)', 'Nondisplaced segmental fracture of shaft of left fibula, initial encounter for closed fracture', 'Aggie Thebeau');
insert into MOCK_DATA (title, description, author) values ('Africa: Texas Style', 'Injury of heart', 'Glendon Charville');
insert into MOCK_DATA (title, description, author) values ('I Hate Valentine''s Day', 'Open bite of left breast', 'Melva Dwine');
insert into MOCK_DATA (title, description, author) values ('Double Wedding', 'Displaced fracture of neck of first metacarpal bone, left hand, initial encounter for closed fracture', 'Roze Mileham');
insert into MOCK_DATA (title, description, author) values ('At Home by Myself... with You', 'Driver of heavy transport vehicle injured in collision with heavy transport vehicle or bus in traffic accident, sequela', 'Stormy Mateescu');
insert into MOCK_DATA (title, description, author) values ('From Hell', 'Age-related osteoporosis with current pathological fracture, left lower leg, subsequent encounter for fracture with routine healing', 'Crissie Yakushkin');
insert into MOCK_DATA (title, description, author) values ('Biutiful', 'Toxic effect of halogenated insecticides, undetermined, sequela', 'Cornelle Gobourn');
insert into MOCK_DATA (title, description, author) values ('Little Girl Who Lives Down the Lane, The', 'Vitamin A deficiency with corneal ulceration and xerosis', 'Fara Jammes');
insert into MOCK_DATA (title, description, author) values ('Marie Antoinette', 'Drowning and submersion due to unspecified watercraft overturning, initial encounter', 'Libbey Minget');
insert into MOCK_DATA (title, description, author) values ('Brainstorm', 'Adverse effect of other nonopioid analgesics and antipyretics, not elsewhere classified, sequela', 'Romona Greyes');
insert into MOCK_DATA (title, description, author) values ('Negotiator, The', 'Contact with hot household appliance, undetermined intent, initial encounter', 'Darnell Peniman');
insert into MOCK_DATA (title, description, author) values ('Seaside (Bord de Mer)', 'Salter-Harris Type I physeal fracture of lower end of humerus, unspecified arm, initial encounter for closed fracture', 'Lida Leming');
insert into MOCK_DATA (title, description, author) values ('Objective, The', 'Puncture wound without foreign body of anus, sequela', 'Moira Corps');
insert into MOCK_DATA (title, description, author) values ('Balto', 'Other traumatic displaced spondylolisthesis of sixth cervical vertebra, subsequent encounter for fracture with delayed healing', 'Eilis Jursch');
insert into MOCK_DATA (title, description, author) values ('Sunny (Sseo-ni)', 'Coma scale, best motor response, localizes pain, at hospital admission', 'Lurleen Parncutt');
insert into MOCK_DATA (title, description, author) values ('Cowboy del Amor', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against unspecified object, initial encounter', 'Cyndi Kytter');
insert into MOCK_DATA (title, description, author) values ('Betty', 'Sprain of right rotator cuff capsule, subsequent encounter', 'Alta Rodolf');
insert into MOCK_DATA (title, description, author) values ('Thin Man Goes Home, The', 'Posterior tibial tendinitis, left leg', 'Jasun Kanter');
insert into MOCK_DATA (title, description, author) values ('Attila Marcel', 'Osteonecrosis due to previous trauma, unspecified femur', 'Frans Pacitti');
insert into MOCK_DATA (title, description, author) values ('How to Irritate People', 'Unspecified focal traumatic brain injury with loss of consciousness of 6 hours to 24 hours, sequela', 'Bartlet Featherstone');
insert into MOCK_DATA (title, description, author) values ('Vincent', 'Penetrating wound of orbit with or without foreign body, left eye, subsequent encounter', 'El Ambrosetti');
insert into MOCK_DATA (title, description, author) values ('Misérables, Les', 'Puncture wound of abdominal wall without foreign body, periumbilic region without penetration into peritoneal cavity, sequela', 'Wilmer Sutliff');
insert into MOCK_DATA (title, description, author) values ('Scandal', 'Injury of right internal carotid artery, intracranial portion, not elsewhere classified with loss of consciousness of 31 minutes to 59 minutes', 'Shannan Minchinton');
insert into MOCK_DATA (title, description, author) values ('Batman & Robin', 'Laceration with foreign body of unspecified great toe without damage to nail', 'Ashli Pisco');
insert into MOCK_DATA (title, description, author) values ('Bound by Flesh ', 'Toxic effect of glycols, undetermined', 'Chrissie Raeburn');
insert into MOCK_DATA (title, description, author) values ('As Far As My Feet Will Carry Me (So weit die Füße tragen)', 'Underdosing of other viral vaccines, subsequent encounter', 'Melisse Pryke');
insert into MOCK_DATA (title, description, author) values ('Naked City, The', 'Other congenital malformations of anterior segment of eye', 'Kip Jaher');